[discogs]
  token = "" # Obtain an API token from Discogs and add it here

[influxdb]
  host = "http://0.0.0.0"
  port = 8086

  # InfluxDB
  # token = ""
  # org = ""
  # bucket = ""

[releases]
  monitored = [] # An array of numbers, where the numbers are release IDs that you can get from Discogs URLs
